version: "3"

services:
  api:
    build: .
    container_name: url_shortener-microservice
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
         - .env
    command: uvicorn url_shortener.app:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5455:5455'
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: